# SPDX-FileCopyrightText: 2017-2025 GodoFredo <hello@godofredo.ninja>
# SPDX-FileCopyrightText: 2025-2026 Pavel Dimov <hello@dimov.xyz>
# SPDX-License-Identifier: GPL-3.0-or-later

routes:
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account
  /membership/: members/membership

  /archive/:
    controller: channel
    filter: 'tag:-[hash-portfolio,hash-kusi-doc]'
    limit: all
    template: archive

  /personal/:
    template: home-personal
    data: page.home-personal

  /podcast/rss/:
    template: podcast/rss
    content_type: text/xml

collections:
  # PortFolio
  /portafolio/:
    permalink: /portafolio/{slug}/
    filter: 'tag:[hash-portfolio]'
    data: page.porftfolio
    template: portfolio
    limit: all

  # Podcast
  /podcast/:
    permalink: /podcast/{slug}/
    filter: 'tag:[hash-podcast]'
    data: page.podcast
    template: podcast
    limit: 10

  # Documentation
  /docs/:
    permalink: /docs/{slug}/
    filter: 'tag:[hash-kusi-doc]'
    template: custom-kusi-doc

  # Default
  /:
    permalink: /{slug}/
    filter: 'tag:-[hash-portfolio,hash-kusi-doc,hash-podcast]'
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
