# SPDX-FileCopyrightText: 2026 Pavel Dimov <pavel@dimov.xyz>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Deploy Dev Theme
on:
  push:
    branches:
      - dev
jobs:
  Deploy-Theme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Deploy Theme
        uses: TryGhost/action-deploy-theme@b1ff2a5eeac1d5438a0aab35eb996fe4010d889e # v2
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
