# SPDX-FileCopyrightText: 2025 2017-2025 GodoFredo <hello@godofredo.ninja>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Deploy Dev Theme
on:
  push:
    branches:
      - dev
jobs:
  Deploy-Theme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Deploy Theme
        uses: TryGhost/action-deploy-theme@v2
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
